theme: jekyll-theme-slate
title: Expressions of interest
description: personal professional blog by Sander Evers
repository: sanderevers/sanderevers.github.io
github:
  is_project_page: false
excerpt_separator: <!--more-->
exclude: [.idea]
